apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: nagarro
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
    nodePort: 31000
  selector:
    k8s-app: kibana-logging
